# Generated by Django 4.2.20 on 2025-05-11 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ListEmp', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='positions',
            table='positions',
        ),
    ]
