# Generated by Django 4.2.20 on 2025-11-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListEmp', '0003_alter_category_table_alter_positions_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_position', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'gender',
                'managed': False,
            },
        ),
    ]
